settings:
  output:
    database:
      url: '127.0.0.1'
      port: 27017
      database: 'tweetdb'
      collection: 'tweets'
  search:
    query: '#burgerlovers'
    params:
  interval:
    each: 'day'
    amount: 1
